CREATE TABLE CANDIDATOS (
    NUM_BOLETA VARCHAR2(30) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELL_PATERNO VARCHAR2(30) NOT NULL,
    APELL_MAT VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    CELULAR VARCHAR2(15) NOT NULL,
    CARRERA VARCHAR2(20) NOT NULL,
    GENERACION VARCHAR2(8) NOT NULL,
    DIRECTOR_TESIS VARCHAR2(50) NOT NULL,
    TEMA_TESIS VARCHAR2(60) NOT NULL,
    TRABAJA VARCHAR2(4) ,
    LUGAR_TRABAJO VARCHAR2(60),
    HORARIO_TRABAJO VARCHAR2(30),
    IMAGEN BLOB NOT NULL,
    CONSTRAINT PK_CANDIDATOS PRIMARY KEY(NUM_BOLETA)
);
commit;

CREATE TABLE ASESORES(

NOMBRE VARCHAR2(30) NOT NULL,
APELL_PATERNO VARCHAR2(30) NOT NULL,
APELL_MAT VARCHAR2(30) NOT NULL,
CUBICULO VARCHAR2(9) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
HORARIO VARCHAR2(30) NOT NULL,
CONSTRAINT PK_ASESORES PRIMARY KEY (EMAIL) 
);



