/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.Candidato;
import Conexion.DBConexion;
import controlador.CandidatoDAO;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Candidatos extends javax.swing.JFrame {
    String  ruta ="";
    CandidatoDAO canHelp;
    DBConexion db;

    /**
     * Creates new form Candidatos
     */
    public Candidatos() {
        initComponents();
        
        canHelp=new CandidatoDAO();
        db=new DBConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreC = new javax.swing.JLabel();
        ApellidoMC = new javax.swing.JLabel();
        ApellidoPC = new javax.swing.JLabel();
        Boleta = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        CelularC = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        Generacion = new javax.swing.JLabel();
        Tema = new javax.swing.JLabel();
        Director = new javax.swing.JLabel();
        txtNomC = new javax.swing.JTextField();
        txtApMatC = new javax.swing.JTextField();
        txtAppC = new javax.swing.JTextField();
        txtBoleta = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtGeneracio = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        txtDirtesis = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        Trabajo = new javax.swing.JLabel();
        Horario = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        txtHorario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkNO = new javax.swing.JCheckBox();
        checkSI = new javax.swing.JCheckBox();
        txtLugarTrabajo = new javax.swing.JTextField();
        txtHorario2 = new javax.swing.JTextField();
        lblhorario = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NombreC.setText("Nombre");

        ApellidoMC.setText("Apellido M");

        ApellidoPC.setText("Apellido P");

        Boleta.setText("Boleta");

        Correo.setText("Correo Electronico");

        CelularC.setText("Celular");

        Carrera.setText("Carrera");

        Generacion.setText("Generacion");

        Tema.setText("Tema de Tesis");

        Director.setText("Director de Tesis");

        txtDirtesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirtesisActionPerformed(evt);
            }
        });

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-de-archivo-de-foto_21208391.jpg"))); // NOI18N
        lblFoto.setText("      FOTO");

        Trabajo.setText("Trabaja :");

        Horario.setText("Horario :");

        Lugar.setText(" Lugar :");

        txtHorario1.setEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo-UACM@2x.png"))); // NOI18N
        jLabel1.setFocusTraversalPolicyProvider(true);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("CANDIDATOS");

        checkNO.setText("NO");
        checkNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkNOMouseClicked(evt);
            }
        });

        checkSI.setText("SI");
        checkSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkSIMouseClicked(evt);
            }
        });

        txtLugarTrabajo.setEnabled(false);

        txtHorario2.setEnabled(false);

        lblhorario.setText("a");

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ApellidoMC)
                                    .addComponent(ApellidoPC)
                                    .addComponent(NombreC))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAppC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApMatC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CelularC)
                                    .addComponent(Correo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Generacion)
                                    .addComponent(Tema)
                                    .addComponent(Director)
                                    .addComponent(Carrera)
                                    .addComponent(Boleta))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCarrera)
                                            .addComponent(txtGeneracio)
                                            .addComponent(txtTema)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDirtesis))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkSI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkNO))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhorario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(Lugar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(185, 185, 185)
                                    .addComponent(btnCancelar))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnRegistrar)
                                    .addGap(179, 179, 179))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnAgregar))
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ApellidoPC)
                                    .addComponent(txtAppC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreC)
                                .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoMC)
                            .addComponent(txtApMatC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CelularC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boleta))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carrera))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeneracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Generacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirtesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Director))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNO)
                    .addComponent(checkSI)
                    .addComponent(Trabajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugar)
                    .addComponent(txtLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horario)
                    .addComponent(txtHorario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhorario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDirtesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirtesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirtesisActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setCurrentDirectory(new File("Imagenes/"));
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if (o == JFileChooser.APPROVE_OPTION) {
            ruta = elegirImagen.getSelectedFile().getAbsolutePath();
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if (preview != null) {
                lblFoto.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
                lblFoto.setIcon(icon);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void checkSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSIMouseClicked
        // TODO add your handling code here:
        if(checkSI.isSelected())
        {   
            checkSI.getText();
            checkNO.setSelected(false);
            txtHorario1.setEnabled(true);
            txtHorario2.setEnabled(true);
            txtLugarTrabajo.setEnabled(true);
        }
                
    }//GEN-LAST:event_checkSIMouseClicked

    private void checkNOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNOMouseClicked
        // TODO add your handling code here:
        if(checkNO.isSelected())
            checkNO.getText();
            checkSI.setSelected(false);
        txtHorario1.setEnabled(false);
            txtHorario2.setEnabled(false);
            txtLugarTrabajo.setEnabled(false);
        
    }//GEN-LAST:event_checkNOMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        if (txtBoleta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Boleta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         if (txtNomC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Nombre", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
          if (txtAppC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Apellido Paterno", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
          if (txtApMatC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Apellido Materno", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
          
         if (txtCarrera.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Carrera", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
          if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Numero de Celular", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
           if (txtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Correo Electronico", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
           
         if (txtDirtesis.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Director Tesis", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
         if (txtTema.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Tema de Tesis", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }  
         
         if ( txtLugarTrabajo.isEnabled()&& txtLugarTrabajo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Lugar de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         if ( txtHorario1.isEnabled()&& txtHorario1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Horario de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         if ( txtHorario2.isEnabled()&& txtHorario2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falto agregar Horario de Trabajo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
         
         String imagen = ruta;
         
         String nombre =txtNomC.getText();
         String aPat=txtApMatC.getText();
         String aMat=txtApMatC.getText();
         String boleta=txtBoleta.getText();
         String email=txtCorreo.getText();
         String celular=txtCelular.getText();
         String carrera=txtCarrera.getText();
         String generacion=txtGeneracio.getText();
         String dirTesis=txtDirtesis.getText();
         String temTesis=txtTema.getText();
         String trabaja=checkSI.getText()+checkNO.getText();
         
         String lugTrabajo=txtLugarTrabajo.getText();
         String horTrabajo=txtHorario1.getText()+lblhorario.getText()+txtHorario2.getText();
         
         
         Candidato candi =new Candidato(imagen, nombre, aPat, aMat, boleta, email, celular, carrera, generacion, temTesis, dirTesis, trabaja, lugTrabajo, horTrabajo);
         
         if (!ruta.equals("")) {
            
                if (canHelp.guardarImagen(candi)) {
                    JOptionPane.showMessageDialog(null, "Candidato fue Guardada Exitosamente en la Base de Datos", "Hecho", JOptionPane.INFORMATION_MESSAGE);
//                txtTitulo.setText("");
//                txtDirector.setText("");
//                txtActorP.setText("");
//                txtGenero.setText("");
//                txtPrecio.setText("");
//                lblimagen.setIcon(null);
                ruta = "";
//                v.visualizar_tabla(tabla);
                return;
                } else {
                    JOptionPane.showMessageDialog(null, "Candidato no pudo ser Guardada en la Base de Datos", "Error", JOptionPane.ERROR_MESSAGE);
                }
             
        } else {
            JOptionPane.showMessageDialog(null, "Te falta Agregar la foto", "Error", JOptionPane.ERROR_MESSAGE);
        }
         
         


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:}
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMC;
    private javax.swing.JLabel ApellidoPC;
    private javax.swing.JLabel Boleta;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel CelularC;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Director;
    private javax.swing.JLabel Generacion;
    private javax.swing.JLabel Horario;
    private javax.swing.JLabel Lugar;
    private javax.swing.JLabel NombreC;
    private javax.swing.JLabel Tema;
    private javax.swing.JLabel Trabajo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox checkNO;
    private javax.swing.JCheckBox checkSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JTextField txtApMatC;
    private javax.swing.JTextField txtAppC;
    private javax.swing.JTextField txtBoleta;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDirtesis;
    private javax.swing.JTextField txtGeneracio;
    private javax.swing.JTextField txtHorario1;
    private javax.swing.JTextField txtHorario2;
    private javax.swing.JTextField txtLugarTrabajo;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables
}
